### PR TITLE
Exception handling

### LINKED ISSUE #6: [DEV] Setup Exception Handling for Study Plan Service
- As part of the US, create a custom exception for Study Plan Service.
- Exceptions should have an error code, error types (Application / Validation)

### LINKED ISSUE #7: [DEV] Implement Global Exception Handler and Create Error Response.
- Explore @ControllerAdvice
- Create a global exception handler which can map the exceptions to error response bodies according to different error types.

Eg: 

**error: {
code: 'NYFC_ERR_COURSE_DOES_NOT_EXISTS',
type: 'Validation'
message: 'The course xyz does not exists. Please check the course name again'
}**

### PR DESCRIPTION
**Pull request by roopa1099**

### CODE REVIEW

File: src/main/java/com/nfyc/studyplanservice/utl/StudyPlanUtil.java [hunk 1]
```diff
@@ -0,0 +1,13 @@
+package com.nfyc.studyplanservice.utl;
+
+import java.util.UUID;
+
+public class StudyPlanUtil {
+
+  final static String UUID_PATTERN="^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$";
+
+  public static Boolean isValidUUID(UUID uuid) {
```
Comment (adityashukla11) [inline src/main/java/com/nfyc/studyplanservice/utl/StudyPlanUtil.java]: As discussed, the UUID validation is not required. Let's remove this function ( and also the class) going forward.

File: src/main/java/com/nfyc/studyplanservice/services/impl/TopicServiceImpl.java [hunk 2]
```diff
@@ -9,56 +11,118 @@
...
-    @Override
-    public TopicDTO getTopicByID(UUID topicID) {
+  @Override
+  public TopicDTO getTopicByID(UUID topicID) throws NyfcException {
+
+    try {
+      if (isValidUUID(topicID)) {
         return topicRepository.findById(topicID).map(topicMapper::topicToTopicDTO).
-                orElseThrow(() -> new RuntimeException("Topic Not Found"));
+          orElseThrow(() -> new NyfcException(ErrorCode.NYFC_ERR_NOT_FOUND, "topic", "id"));
```
Comment (adityashukla11) [inline src/main/java/com/nfyc/studyplanservice/services/impl/TopicServiceImpl.java]: Better to send the actual value of topicId also which was not found
`orElseThrow(() -> new NyfcException(ErrorCode.NYFC_ERR_NOT_FOUND, "topic", "id"));`

Please change the error code message to: "The %s with given %s : %s was not found"

File: src/main/java/com/nfyc/studyplanservice/services/impl/TopicServiceImpl.java [hunk 3]
```diff
@@ -9,56 +11,118 @@
...
+  private final TopicRepository topicRepository;
+  private final TopicMapper topicMapper;
 
-    @Override
-    public TopicDTO getTopicByID(UUID topicID) {
+  @Override
+  public TopicDTO getTopicByID(UUID topicID) throws NyfcException {
+
+    try {
+      if (isValidUUID(topicID)) {
```
Comment (adityashukla11) [inline src/main/java/com/nfyc/studyplanservice/services/impl/TopicServiceImpl.java]: Let us remove the UUID validations as it might not be needed.

File: src/main/java/com/nfyc/studyplanservice/services/impl/TopicServiceImpl.java [hunk 4]
```diff
@@ -9,56 +11,118 @@
...
+      throw new NyfcException(ErrorCode.NYFC_ERR_DATABASE_EXCEPTION, exception.getMessage());
     }
 
-    @Override
-    public  List<TopicDTO> getTopicByCourseID(UUID courseID){
-        return topicRepository.findTopicsByCourse_CourseID(courseID).stream().map(topicMapper::topicToTopicDTO).collect(Collectors.toList());
+  }
+
+  @Override
+  @Transactional
```
Comment (adityashukla11) [inline src/main/java/com/nfyc/studyplanservice/services/impl/TopicServiceImpl.java]: Since we only make read-only calls in the method, can we use `@Transactional(readOnly = true) `

Also can the annotation be added in the Interface ? Not sure.

File: src/main/java/com/nfyc/studyplanservice/services/impl/StudyPlanServiceImpl.java [hunk 5]
```diff
@@ -29,55 +29,59 @@
...
-        if (!violations.isEmpty()) {
-            StringBuilder sb = new StringBuilder();
-            for (ConstraintViolation<FilterRequestListDTO> constraintViolation : violations) {
-                sb.append(constraintViolation.getMessage());
-            }
-            throw new ConstraintViolationException("Error occurred: " + sb.toString(), violations);
-        }
-        return filterRequestListDTO;
+    if (!filter.get(filterCondition).isArray()) {
+      throw new RuntimeException("Given Condition " + filterCondition + " is not an array");
```
Comment (adityashukla11) [inline src/main/java/com/nfyc/studyplanservice/services/impl/StudyPlanServiceImpl.java]: Please replace it with NFYCException.

File: src/main/java/com/nfyc/studyplanservice/services/impl/StudyPlanServiceImpl.java [hunk 6]
```diff
@@ -29,55 +29,59 @@
...
+    FilterRequestListDTO filterRequestListDTO = objectMapper.convertValue(requestBody.get("data").get("filter"),
+      typeReference);
+    filterRequestListDTO.setFilterCondition(filterCondition);
+    Set<ConstraintViolation<FilterRequestListDTO>> violations = validator.validate(filterRequestListDTO);
+    if (!violations.isEmpty()) {
+      StringBuilder sb = new StringBuilder();
+      for (ConstraintViolation<FilterRequestListDTO> constraintViolation : violations) {
+        sb.append(constraintViolation.getMessage());
+      }
+      throw new ConstraintViolationException("Error occurred: " + sb.toString(), violations);
```
Comment (adityashukla11) [inline src/main/java/com/nfyc/studyplanservice/services/impl/StudyPlanServiceImpl.java]: Please replace it with NFYCException.

File: src/main/java/com/nfyc/studyplanservice/services/impl/CourseServiceImpl.java [hunk 7]
```diff
@@ -14,57 +14,95 @@
...
+  public void deleteCourse(UUID courseID) throws NyfcException {
+    try {
+      if (isValidUUID(courseID)) {
+        Course retrievedCourse = courseRepository.findById(courseID)
+          .orElseThrow(() -> new NyfcException(ErrorCode.NYFC_ERR_NOT_FOUND, "course", "id"));
         courseRepository.delete(retrievedCourse);
+      } else {
+        throw new NyfcException(ErrorCode.NYFC_ERR_REQUEST_INVALID);
+      }
+      ;
```
Comment (adityashukla11) [inline src/main/java/com/nfyc/studyplanservice/services/impl/CourseServiceImpl.java]: Please fix the formatting.

File: src/main/java/com/nfyc/studyplanservice/services/impl/CourseServiceImpl.java [hunk 8]
```diff
@@ -14,57 +14,95 @@
...
 
-    @Override
-    public void deleteCourse(UUID courseID) {
-        Course retrievedCourse = courseRepository.findById(courseID).orElseThrow(() -> new RuntimeException("Course Not Found"));
+  @Override
+  public void deleteCourse(UUID courseID) throws NyfcException {
+    try {
+      if (isValidUUID(courseID)) {
+        Course retrievedCourse = courseRepository.findById(courseID)
+          .orElseThrow(() -> new NyfcException(ErrorCode.NYFC_ERR_NOT_FOUND, "course", "id"));
```
Comment (adityashukla11) [inline src/main/java/com/nfyc/studyplanservice/services/impl/CourseServiceImpl.java]: Better to send the actual value of courseID also which was not found
`orElseThrow(() -> new NyfcException(ErrorCode.NYFC_ERR_NOT_FOUND, "course", "id"));`

Please change the error code message to: "The %s with given %s : %s was not found"

File: src/main/java/com/nfyc/studyplanservice/services/impl/CourseServiceImpl.java [hunk 9]
```diff
@@ -14,57 +14,95 @@
...
-        Page<CourseDTO> courseDTOPage=courseRepository.findAll(pageable).stream().map(courseMapper::courseToCourseDTO).collect(Collectors.collectingAndThen(Collectors.toList(), PageImpl::new));
-        return courseDTOPage;
+  public Page<CourseDTO> getAllCourses(int page, int size) throws NyfcException {
+    try {
+      Pageable pageable = PageRequest.of(page, size);
+      Page<CourseDTO> courseDTOPage = courseRepository.findAll(pageable).stream()
+        .map(courseMapper::courseToCourseDTO)
+        .collect(Collectors.collectingAndThen(Collectors.toList(), PageImpl::new));
+      return courseDTOPage;
+    } catch (Exception exception) {
```
Comment (adityashukla11) [inline src/main/java/com/nfyc/studyplanservice/services/impl/CourseServiceImpl.java:33]: do we need to catch a exception here ?

File: src/main/java/com/nfyc/studyplanservice/exception/NyfcErrorResponse.java [hunk 10]
```diff
@@ -0,0 +1,23 @@
...
+import lombok.Builder;
+import lombok.Data;
+import lombok.NoArgsConstructor;
+
+import javax.validation.constraints.NotNull;
+
+@Data
+@Builder
+@NoArgsConstructor
+@AllArgsConstructor
```
Comment (adityashukla11) [inline src/main/java/com/nfyc/studyplanservice/exception/NyfcErrorResponse.java:13]: Since all fields are `@NonNull`, do we require `@AllArgsConstructor`. 

I guess `@RequiredArgsConstructor` (as part of `@Data` ) is enough.

File: src/main/java/com/nfyc/studyplanservice/exception/NfycExceptionHandler.java [hunk 11]
```diff
@@ -0,0 +1,26 @@
...
+import org.springframework.web.bind.annotation.ControllerAdvice;
+import org.springframework.web.bind.annotation.ExceptionHandler;
+import org.springframework.web.bind.annotation.ResponseBody;
+import org.springframework.web.bind.annotation.ResponseStatus;
+
+@ControllerAdvice
+public class NfycExceptionHandler{
+
+    @ExceptionHandler(NyfcException.class)
+    @ResponseStatus(HttpStatus.NOT_FOUND)
```
Comment (adityashukla11) [inline src/main/java/com/nfyc/studyplanservice/exception/NfycExceptionHandler.java]: Should we send NOT_FOUND for all exceptions ?

File: src/main/java/com/nfyc/studyplanservice/exception/NyfcException.java [hunk 12]
```diff
@@ -0,0 +1,17 @@
...
+    NyfcErrorResponse errorResponse;
+    public NyfcException(ErrorCode errorCode, String... params){
+        errorResponse=new NyfcErrorResponse(errorCode.toString(),String.format(errorCode.getMessage(),params),errorCode.getErrorType().toString());
+    }
+    @Override
+    public String getMessage() {
+        return errorResponse.getMessage();
+    }
+
+    public NyfcErrorResponse getError(){
```
Comment (adityashukla11) [inline src/main/java/com/nfyc/studyplanservice/exception/NyfcException.java]: `@Getter` can be used, on `NyfcErrorResponse errorResponse` instead of this function

File: src/main/java/com/nfyc/studyplanservice/exception/NyfcErrorResponse.java (hunk 10 above)
Comment (roopa1099) [reply src/main/java/com/nfyc/studyplanservice/exception/NyfcErrorResponse.java:13]: No, fields are not fnal.

File: src/main/java/com/nfyc/studyplanservice/exception/NyfcException.java (hunk 12 above)
Comment (roopa1099) [reply src/main/java/com/nfyc/studyplanservice/exception/NyfcException.java]: Fixed

File: src/main/java/com/nfyc/studyplanservice/exception/NfycExceptionHandler.java (hunk 11 above)
Comment (roopa1099) [reply src/main/java/com/nfyc/studyplanservice/exception/NfycExceptionHandler.java]: Removed

File: src/main/java/com/nfyc/studyplanservice/services/impl/CourseServiceImpl.java (hunk 9 above)
Comment (roopa1099) [reply src/main/java/com/nfyc/studyplanservice/services/impl/CourseServiceImpl.java:33]: For all scneario, prefered adding a standard error format

File: src/main/java/com/nfyc/studyplanservice/services/impl/CourseServiceImpl.java (hunk 8 above)
Comment (roopa1099) [reply src/main/java/com/nfyc/studyplanservice/services/impl/CourseServiceImpl.java]: Done

File: src/main/java/com/nfyc/studyplanservice/services/impl/CourseServiceImpl.java (hunk 7 above)
Comment (roopa1099) [reply src/main/java/com/nfyc/studyplanservice/services/impl/CourseServiceImpl.java]: Done

File: src/main/java/com/nfyc/studyplanservice/services/impl/StudyPlanServiceImpl.java (hunk 6 above)
Comment (roopa1099) [reply src/main/java/com/nfyc/studyplanservice/services/impl/StudyPlanServiceImpl.java]: Done

File: src/main/java/com/nfyc/studyplanservice/services/impl/StudyPlanServiceImpl.java (hunk 5 above)
Comment (roopa1099) [reply src/main/java/com/nfyc/studyplanservice/services/impl/StudyPlanServiceImpl.java]: Done

File: src/main/java/com/nfyc/studyplanservice/services/impl/TopicServiceImpl.java (hunk 4 above)
Comment (roopa1099) [reply src/main/java/com/nfyc/studyplanservice/services/impl/TopicServiceImpl.java]: Changed logic

File: src/main/java/com/nfyc/studyplanservice/services/impl/TopicServiceImpl.java (hunk 2 above)
Comment (roopa1099) [reply src/main/java/com/nfyc/studyplanservice/services/impl/TopicServiceImpl.java]: Done

File: src/main/java/com/nfyc/studyplanservice/utl/StudyPlanUtil.java (hunk 1 above)
Comment (roopa1099) [reply src/main/java/com/nfyc/studyplanservice/utl/StudyPlanUtil.java]: Done

**Review by adityashukla11 — APPROVED** [review]
